name: Release testing
on:
  push:
    branches:
      - master
      - auto-updater
# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@v1
#         with:
#           node-version: "12.x"
#       - run: npm ci
#       - run: npm run build --if-present
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetching version from package.json
        shell: pwsh
        run: |
          $version = node -p "require('./package.json').version"
          echo "VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Release version number
        run: |
          echo "${{ env.VERSION }}"
      - name : Getting commit hash
        shell: bash
        run: |
          echo "COMMIT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Printing commit hash 8 first characters
        run: |
          echo "The sha: "
          echo "${{env.COMMIT_SHA}}"
#       - name: navigating
#         uses: actions/setup-node@v1
#         with: 
#           node-version: "12.x"
#       - run: |
#             mkdir test
#             ls
#             cp index.js ./test
#             cd test
#             ls
      - name: Create Release
        id: create_release
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token comes from package.json
        with:
          tag_name: v${{env.VERSION}}-${{env.COMMIT_SHA}} # ex: v1.0.0-abcd1234
          release_name: v${{env.VERSION}}-${{env.COMMIT_SHA}} # same as tag_name
          draft: true
          prerelease: false
      - name: navigating
        uses: actions/setup-node@v1
        with: 
          node-version: "12.x"
      - run: |
            mkdir test
            ls
            cp index.js ./test
            cd test
            ls
