name: Release npm package

on:
  push:
    branches:
      - master
# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@v1
#         with:
#           node-version: "12.x"
#       - run: npm ci
#       - run: npm run build --if-present
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
#     env:
#       VERSION: 1.0.0
    steps:
#       - name: bla
#         if: ${{ env.VERSION == '1.4.7' }}
#         shell: pwsh
#         run: |
#           $vers = node -p "require('./package.json').version"
#           $vers
      - name: Checkout code
        uses: actions/checkout@v2
      - name: check version with shell
        shell: pwsh
        run: |
          $version = node -p "require('./package.json').version"
          $version
          echo "This is the version number bro"
          echo "VERSION=$version" > $GITHUB_ENV
          echo "${{ env.VERSION }}"
          ${{ env.VERSION }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
#           tag_name: node -p "require('./package.json').version"
          tag_name: v${{env.VERSION}} # ${{ github.ref }}
          release_name: v${{env.VERSION}}
#           release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: true
